### ISSUE TITLE
Console Spam with Error Executing Task

### ISSUE THREAD

**Issue by Osprey4444** [TheRandomLabs/RandomPatches#77] opened 2019-12-15 00:29 UTC
```
> [01:26:37] [Server thread/FATAL] [minecraft/MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: com.therandomlabs.randompatches.hook.PlayerInteractionManagerHook.sendBlockChangePacket(Lnet/minecraft/server/management/PlayerInteractionManager;Lnet/minecraft/util/math/BlockPos;)V
at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_212]
at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_212]
at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.NoSuchMethodError: com.therandomlabs.randompatches.hook.PlayerInteractionManagerHook.sendBlockChangePacket(Lnet/minecraft/server/management/PlayerInteractionManager;Lnet/minecraft/util/math/BlockPos;)V
at net.minecraft.server.management.PlayerInteractionManager.func_180784_a(PlayerInteractionManager.java:222) ~[or.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:693) ~[pa.class:?]
at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:40) ~[lp.class:?]
at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:10) ~[lp.class:?]
at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_212]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_212]
at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
... 5 more
```

**Comment by TheRandomLabs** [comment] 2019-12-15 00:47
Duplicate of #76.

**Closed as completed by TheRandomLabs** 2019-12-15 00:47 UTC
