### ISSUE TITLE
[1.12.2] Potion particles fix overrides a Dynamic Surroundings setting

### ISSUE THREAD

**Issue by Cre8or** [TheRandomLabs/RandomPatches#47] opened 2019-08-02 13:35 UTC
Hello!

I'm using RandomPatches alongside Dynamic Surroundings, and I've noticed that enabling the Particles fixes overrides Dynamic Surroundings' "Suppress Potion Particles" setting (under "Player Options"), causing potion particles to show on the player.

Ideally, the player's potion effects should still be suppressed when using both mods in this configuration.

**Versions used:**
* Minecraft 1.12.2
* Minecraft Forge v14.23.5.2836
* RandomPatches v1.17.2.1
* DynamicSurroundings v3.5.4.3

**Comment by TheRandomLabs** [comment] 2019-08-03 13:19
The flag Dynamic Surroundings is using, `EntityLivingBase#HIDE_PARTICLES`, doesn't actually disable particles. I'm not entirely sure why, as I haven't performed a thorough investigation, but without RandomPatches installed, the game is still trying to create particles and failing. RandomPatches simply fixes the particles not spawning correctly. Since OreCruncher seems to be inactive, I'll see if I can work around this later.

**Comment by TheRandomLabs** [comment] 2019-10-04 06:19
Sorry for the late response, but I think the best option for now would be to use [CleanView](https://www.curseforge.com/minecraft/mc-mods/cleanview).

**Comment by zlainsama** [comment] 2019-10-22 09:36
@TheRandomLabs 
https://github.com/zlainsama/CleanView/issues/7
Unfortunately, CleanView doesn't work with RandomPatches.
I might be wrong, but with the patch, entities' potion particles might be doubled.

**Comment by TheRandomLabs** [comment] 2019-10-22 09:40
Oh dear, I'll look at this as soon as I can.

**Comment by TheRandomLabs** [comment] 2020-01-19 03:42
Sorry, I kinda forgot about this issue. :P
The issue is that both CleanView and Dynamic Surroundings only work on the `EntityPlayerSP` instance but don't work on the `EntityPlayerMP` instance.~~; hence, this is only relevant in singleplayer worlds.~~
**EDIT:** It should be clarified that they only work on the client-sided player instance and do not work on the server-sided player instance.

**Comment by zlainsama** [comment] 2020-01-19 07:00
@TheRandomLabs 
That is not true, client and server are separated even in singleplayer.
This problem happens on both singleplayer and multiplayer.

**Comment by TheRandomLabs** [comment] 2020-01-19 07:35
Perhaps I missed something while testing. I'll try again.
**EDIT:** CleanView works normally with just RandomPatches when connected to a dedicated server without RandomPatches. If RandomPatches is installed on the server, it stops working.

**Comment by TheRandomLabs** [comment] 2020-01-19 07:44
If I'm not mistaken, the game attempts to spawn particles on both the client and the server, but the server particles aren't spawning correctly due to MC-10369. This is fixed by RandomPatches, which is causing CleanView and Dynamic Surroundings to fail.

**Comment by TheRandomLabs** [comment] 2020-01-19 07:56
[Fixed](https://github.com/TheRandomLabs/RandomPatches/blob/845f194473908b62d2de69dc5f6d0b621a36c2eb/src/main/java/com/therandomlabs/randompatches/hook/ServerWorldEventHandlerHook.java#L17-L25). :)

**Closed as completed** 2020-01-19 07:56 UTC
Labels: low priority
