### ISSUE TITLE
Icon config doesn't work on MacOS

### ISSUE THREAD

**Issue by chinesexs** [TheRandomLabs/RandomPatches#37] opened 2019-06-25 13:23 UTC
Well one of my friends was using MacOS to play minecraft with this mod
Here's more informations about the game:
Minecraft version 1.12.2
Forge version 2838
RP version 1.16.2.1
The Icon config just do nothing!
The config file was used utf-8 so it has nothing to do with this

**Comment by TheRandomLabs** [comment] 2019-06-26 05:43
Can you see if [this](https://www.dropbox.com/s/xrtek47fwdh19bw/randompatches-1.12.2-1.16.3.1.jar?dl=0) build works? I don't have a Mac so I can't test it myself.

**Comment by chinesexs** [comment] 2019-07-01 01:37
My friend says it does work,so it seemed to be fixed

**Comment by chinesexs** [comment] 2019-07-04 15:32
Sorry for the last time what i said!
My friend says it still doesn't work,it was my fault,I didn't open QQ to see message so I get it wrong
So you should really find a Mac to fix this problem

**Comment by TheRandomLabs** [comment] 2019-07-05 02:33
Damn, I'll look at this again soon.

**Comment by TheRandomLabs** [comment] 2019-08-11 02:43
I can't get Minecraft running in a Mac OS VM and I don't have access to a Mac. Just to confirm that the issue is with RandomPatches, can I have a copy of your configuration?

**Comment by TheRandomLabs** [comment] 2019-08-21 05:41
I'll close this for now. Open another issue if this is still a problem.

**Closed as completed by TheRandomLabs** 2019-08-21 05:41 UTC
