### ISSUE TITLE
Allow config to disable client.window changes entirely

### ISSUE THREAD

**Issue by aaronhowser1** [TheRandomLabs/RandomPatches#186] opened 2021-01-30 11:20 UTC
KubeJS also supports changing this stuff, and I was wondering why it wasn't working until I searched my entire config folder for "Minecraft %s" 
![image](https://user-images.githubusercontent.com/15698722/106354931-aa90fd80-62ba-11eb-9467-762be1a1ea1c.png)

As far as I can  tell, there's no way to simply disable that part of the config from having any effect. 

This is using `randompatches-2.1.5-forge`

**Comment by aaronhowser1** [comment] 2021-01-30 11:21
[This is the code that RP is conflicting with btw](https://github.com/KubeJS-Mods/KubeJS/blob/master/common/src/main/java/dev/latvian/kubejs/mixin/common/MinecraftMixin.java)

**Comment by TheRandomLabs** [comment] 2021-02-01 02:00
Duplicate of #184.

**Closed as completed by TheRandomLabs** 2021-02-01 02:00 UTC
