### ISSUE TITLE
1.17.1 support

### ISSUE THREAD

**Issue by MSDNicrosoft** [TheRandomLabs/RandomPatches#242] opened 2021-08-15 15:35 UTC
plz

**Comment by K0-RR** [comment] 2021-08-15 15:36
Duplicate of https://github.com/TheRandomLabs/RandomPatches/issues/236.
Also mentioning the dev when opening an issue is pointless since they already receive a notification about the new issue.

**Closed as completed** 2021-08-15 15:42 UTC
