### ISSUE TITLE
Exception ticking world and TickNextTick list out of synch still happening in the latest 1.12.2 release

### ISSUE THREAD

**Issue by heichang** [TheRandomLabs/RandomPatches#149] opened 2020-12-24 05:50 UTC
I had a Exception ticking world crash in this few day , some people gave me some advice about using RandomPatches to fix it , 
it in Reddit  : 
https://www.reddit.com/r/FeedTheBeastCrashes/comments/kisd0l/crash_because_exception_ticking_world/

but the "Exception ticking world" and "TickNextTick list out of synch" , it's still happening in the latest 1.12.2 release

This is my crash report ：
https://pastebin.com/7jkSJ3t7

Thank you.

**Comment by TheRandomLabs** [comment] 2020-12-25 04:14
Duplicate of #142.

**Closed as completed by TheRandomLabs** 2020-12-25 04:14 UTC
