### ISSUE TITLE
[1.16.3][1.22.1.2] Config Reset on Server Restart

### ISSUE THREAD

**Issue by Kris1432** [TheRandomLabs/RandomPatches#128] opened 2020-11-11 20:42 UTC
I am currently experiencing a config reset on server restarts for;

loginTimeout = 900

I changed it to 90000 to enable people to join, and it stays that way and does its job to let the one person that needs this to get in but on server reboot it keeps going back to 900.

If you need anymore info please let me know!

**Comment by ViRb3** [comment] 2020-11-21 15:58
Dupe of #104

**Closed as completed** 2020-11-27 10:16 UTC
