### ISSUE TITLE
Players CAN'T connect to the server due to this ERROR: Failed to transform class: net.minecraft.network.NetHandlerPlayServer

### ISSUE THREAD

**Issue by ThatOverPowered** [TheRandomLabs/RandomPatches#107] opened 2020-06-28 05:05 UTC
So as the title says RandomPatches is generating this error when the server is loading.

Im using a MAGMA Server (https://magmafoundation.org/) in the version "Magma Dev HEAD-44e91f6"

Server is running in Ubuntu 20.04 with JAVA:

```
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-8u252-b09-1ubuntu1-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)
```

Log ERROR:

```
[05:53:44 ERROR]: Failed to transform class: net.minecraft.network.NetHandlerPlayServer
 java.lang.NullPointerException: null
	at org.objectweb.asm.tree.InsnList.insert(Unknown Source) ~[asm-all-5.2.jar:5.2]
	at com.therandomlabs.randompatches.patch.NetHandlerPlayServerPatch.patchUpdate(NetHandlerPlayServerPatch.java:121) ~[NetHandlerPlayServerPatch.class:?]
	at com.therandomlabs.randompatches.patch.NetHandlerPlayServerPatch.apply(NetHandlerPlayServerPatch.java:26) ~[NetHandlerPlayServerPatch.class:?]
	at com.therandomlabs.randompatches.core.RPTransformer.transform(RPTransformer.java:37) [randompatches-1.12.2-1.21.0.3.jar:?]
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256) [ASMTransformerWrapper$TransformerWrapper.class:44e91f6]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) [?:1.8.0_252]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) [?:1.8.0_252]
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_252]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) [?:1.8.0_252]
	at java.lang.Class.privateGetPublicMethods(Class.java:2902) [?:1.8.0_252]
	at java.lang.Class.getMethods(Class.java:1615) [?:1.8.0_252]
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:81) [EventBus.class:44e91f6]
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:82) [AutomaticEventSubscriber.class:44e91f6]
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:612) [FMLModContainer.class:44e91f6]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [minecraft_server.1.12.2.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219) [LoadController.class:44e91f6]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197) [LoadController.class:44e91f6]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [minecraft_server.1.12.2.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136) [LoadController.class:44e91f6]
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:566) [Loader.class:44e91f6]
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:102) [FMLServerHandler.class:44e91f6]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:335) [FMLCommonHandler.class:44e91f6]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:169) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:684) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
```

**Comment by TheRandomLabs** [comment] 2020-06-28 06:22
Can I have a mod list?

**Comment by ThatOverPowered** [comment] 2020-06-28 18:11
> Can I have a mod list?

Sure: 

```
AI-Inprovements
Aether-Continuation
Aether-Legacy
AppleCore
AppleSkin
Aquaculture
Aroma1997-Dimensional-World
Aroma1997Core
Atum
AutoRegLib
Baubles
BetterAdvancements
BetterAnimalsPlus
BetterDiving
BiblioCraft
Bloodmoon
Bonsaitrees
Bookshelf
Bountiful
BuildingGadgets
CTM-ConnectedTextures
Cavern
Chamaleon
ChanceCubes
Charm
ChestTransporter
ChikenChunks
Chisel
Clumps
CodeChickenLib
ColossalChests
Comforts
CookingForBlockheads
CosmeticArmorReworked
CraftTweaker2
Cucumber
CustomNPCs
CustomizedDungeonLoot
Cyclic
CyclopsCore
DarknessLib
DimensionalDoors
Disenchanter
DoomlikeDungeons
DungeonTactics
ElectroblobsWizardry
EmbersRekindled
Embersified
EnchantmentDescriptions
EngineersWorkshopReborn
ExtraSpells
ExtraUtils2
ExtraalchemyForge
FTB-BackUps
FTB-Guides
FTB-Lib
FTB-Money
FTB-Quest
FTB-Utilities
FastFurnace
FoamFix
Forgelin
Grue
Heroicarmory
Hooked
IceAndFire
ImprovedBackpacks
InfernalMobs
InventoryPets
InventoryTweaks
ItemFilters
IvToolkit
JEI-JustEnoughItems
JackOLauncher
Journeymap
JustEnoughIDs
LLibrary
LevelUp2
LibrarianLib
LibraryEx
ListAetherContent
LivingEnchantment
LoginShield
MegaLoot
MinervaLibrary
MoreMobs
MowziesMobs
MysticalAgradditions
MysticalAgriculture
NatureCompass
NetherEx
NetherPortalFix
NoMoreRecipeConflict
NomadicTents
OpenBlocks
OpenBlocksLib
Optifine
OrdinaryCoins
OreLib
PamsHarvestCraft
Phospor
Placebo
PotionCore 
Prefab
ProgressiveBosses
ProjectVibrantJourneys
PyramidPlunder
QualityTools
Quark
QuarkOddities
RandomLoot
RandomPatches
RandomTweaks
RebornCore
RecurrentComplex
Reliquary
RoguelikeDungeons
Ropebridge
RoughTweaks
Rustic
STG-SwingThroughGrass
ScalingHealth
SecurityCraft
SignPost
SilentLib
SimpleStorageNetwork
Skewers
Solcarrot
SoundFilters
SpartanFire
SpartanShields
SpartanWeaponary
StorageDrawers
Strawgolem
StuffASockInIt
SubterraneanSwitcheroo
Thaumcraft
ThaumicInventoryScanning
The-Beneath
TheBetweenlands
TheEightFabledBlades
Tombstone
Totemic
Tropicraft
Twilightforest
Uniquecrops
VTweaks
VanillaFix
VanillaTweaks
VariedComodities
ViesCraft
WayStones
```

**Comment by TheRandomLabs** [comment] 2020-06-30 23:06
Sorry, could I also have a `debug.log`?

**Comment by LemADEC** [comment] 2020-07-26 19:10
I've similar issue with SpongeForge 1.12.2-2838-7.2.3
Debug logs are here: https://gist.github.com/LemADEC/98084d018d97334880dec01b24558e53

**Comment by LemADEC** [comment] 2020-07-26 20:20
Please note there's also a crash with Piston in there, like so:
```
[14:58:56] [main/ERROR] [randompatches]: Failed to transform class: net.minecraft.tileentity.TileEntityPiston
java.lang.NullPointerException: null
	at org.objectweb.asm.tree.InsnList.insert(InsnList.java:377) ~[asm-debug-all-5.2.jar:5.2]
	at com.therandomlabs.randompatches.patch.TileEntityPistonPatch.patchUpdateGhostBlockFix(TileEntityPistonPatch.java:88) ~[TileEntityPistonPatch.class:?]
	at com.therandomlabs.randompatches.patch.TileEntityPistonPatch.apply(TileEntityPistonPatch.java:24) ~[TileEntityPistonPatch.class:?]
	at com.therandomlabs.randompatches.core.RPTransformer.transform(RPTransformer.java:37) [randompatches-1.12.2-1.22.0.0.jar:?]
```

Both issues are reproduced without SpongeForge.
Both issues are no longer reproduced at boot when removing Farseek-1.12-2.5.jar. Since that mod isn't in original context, there's probably more than meet the eyes.

**Comment by LucidAPs** [comment] 2020-09-23 09:05
I am using mohist i also have this problem.
on server startup
https://hastebin.com/jititocawe.rb
on player login
https://hasteb.in/esanijel.kotlin

**Comment by TheRandomLabs** [comment] 2020-09-24 01:59
Sorry for the late response; it seems I didn't notice that you were using a custom server. :P
@ThatOverPowered This should be fixed now.
@LemADEC I'm not sure what's causing the piston issue at the moment.
@LucidAPs Can I have a debug.log so I can figure out the NettyCompressionDecoder error?

**Closed as completed** 2020-12-13 01:58 UTC
Labels: info
